// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\oviek.ghinulur\go\src\any\go-quantus-service\src\rabbitMQ\rabbitmq.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\oviek.ghinulur\go\src\any\go-quantus-service\src\rabbitMQ\rabbitmq.go -destination=C:\Users\oviek.ghinulur\go\src\any\go-quantus-service\test\mocks\mock_rabbit.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
